version: 2
jobs:
  build:
    filters:
      branches:
          only:
            - master
    docker:
      # specify the version
      - image: hashicorp/terraform

    #region: AWS_DEFAULT_REGION
    steps:
      - checkout
      - run: aws iam list-users --region us-west-2
