version: 2
jobs: 
  plan: 
    filters:
      branches:
        ignore:
           - master
 
    docker:
      # specify the version
      - image: hashicorp/terraform

    #region: AWS_DEFAULT_REGION
    steps:
      - checkout
      - run: terraform plan
      - run: terraform init

workflows:
  version: 2
  plan_and_apply:
    jobs:
      - plan
      - init
