version: 2
jobs:
  build:
    filters:
      branches:
          only:
            - master
    docker:
      # specify the version
      - image: hashicorp/terraform

    #region: AWS_DEFAULT_REGION
    steps:
      - checkout
      - run: terraform --version
  plan:
    filters:
      branches:
          ignore:
            - master
    docker:
      # specify the version
      - image: hashicorp/terraform

    #region: AWS_DEFAULT_REGION
    steps:
      - checkout
      - run: terraform plan
