version: 2
jobs:
  plan:             
    docker:
      - image: hashicorp/terraform
    steps:      
      - checkout
      - run: terraform init
      - run: terraform plan 
  apply: 
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: terraform init
      - run: terraform apply -auto-approve -input=false
  final-plan:             
    docker:
      - image: hashicorp/terraform
    steps:      
      - checkout
      - run: terraform init
      - run: terraform plan 
workflows:
  version: 2
  plan-and-apply:
    jobs:
      - plan:
          filters:
            branches:
              ignore: master
      - apply:
          requires:
            - final-plan
          filters:
            branches:
              only: master
