version: 2
jobs:
  plan:    
    filters:
      branches:
        ignore:
           - master
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: terraform init
      - run: terraform plan
  apply: 
    filters:
      branches:
        only:
           - master
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: terraform init
      - run: terraform apply -auto-approve -input=false
workflows:
  version: 2
  plan-and-apply:
    jobs:
      - plan:
          filters:
            branches:
              ignore: master
      - apply:
          filters:
            branches:
              only: master
