version: 2
jobs:
  build:
    filters:
      branches:
          only:
            - master
    docker:
      # specify the version
      - image: amazon/aws-cli
    region: AWS_DEFAULT_REGION
    steps:
      - checkout
      - run: aws ec2 describe-instances --region us-west-2
