version: 2
jobs:
    init: 
      filters:
        branches:
          ignore:
            - master
    docker:
      # specify the version
      - image: hashicorp/terraform

    #region: AWS_DEFAULT_REGION
    steps:
      - checkout
      - run: terraform init

workflows:
  version: 2
  plan_and_apply:
    jobs:
      - init
